const TS=256,MINZ=7,MAXZ=19,INIT={lon:126.9768,lat:37.4016,zoom:16},R=7,SEN_MED=1,SEN_LOW=2.5,SEN_CRIT=5;
const cvs={map:document.querySelector("#mapCanvas"),cctv:document.querySelector("#cctvCanvas")},ctx={map:cvs.map.getContext("2d"),cctv:cvs.cctv.getContext("2d")};
const ui={cctvImageInput:$("#cctvImageInput"),jsonInput:$("#jsonInput"),showImage:$("#showImage"),showLabels:$("#showLabels"),hideExcludedTin:$("#hideExcludedTin"),useSensitivity:$("#useSensitivity"),edgeLimit:$("#edgeLimit"),edgeValue:$("#edgeValue"),angleLimit:$("#angleLimit"),angleValue:$("#angleValue"),warningOpacity:$("#warningOpacity"),warningOpacityValue:$("#warningOpacityValue"),pointCount:$("#pointCount"),matchedCount:$("#matchedCount"),tinCount:$("#tinCount"),excludedCount:$("#excludedCount"),warningCount:$("#warningCount"),sensitivityCount:$("#sensitivityCount"),qualityAdvice:$("#qualityAdvice"),testResult:$("#testResult"),emptySelection:$("#emptySelection"),pointEditor:$("#pointEditor"),cctvX:$("#cctvX"),cctvY:$("#cctvY"),mapX:$("#mapX"),mapY:$("#mapY"),deletePointBtn:$("#deletePointBtn"),clearBtn:$("#clearBtn"),clearPointsBtn:$("#clearPointsBtn"),exportBtn:$("#exportBtn"),fitBtn:$("#fitBtn"),mapTools:$("#mapTools"),mapToolsToggle:$("#mapToolsToggle"),vworldKeyInput:$("#vworldKeyInput"),vworldApplyBtn:$("#vworldApplyBtn"),kakaoKeyInput:$("#kakaoKeyInput"),roadviewToggleBtn:$("#roadviewToggleBtn"),roadviewRefreshBtn:$("#roadviewRefreshBtn"),roadviewPanel:$("#roadviewPanel"),roadviewStatus:$("#roadviewStatus"),roadviewEl:$("#roadview"),mapTypeButtons:document.querySelectorAll(".map-image-btn[data-map-type]"),rotateLeft:$("#rotateLeftBtn"),rotateRight:$("#rotateRightBtn"),rotateReset:$("#rotateResetBtn"),rotateSlider:$("#rotateSlider"),rotateValue:$("#rotateValue"),modeButtons:document.querySelectorAll(".mode[data-mode]")};
const st={points:[],triangles:[],selectedId:null,mode:"add",drag:null,pan:null,test:null,mapType:"base",nextId:1,images:{cctv:null},roadview:{enabled:false,ready:false,rv:null,client:null,pos:null,viewpoint:null,syncTimer:null},views:{map:{...INIT},cctv:{scale:1,x:0,y:0}}};
let map,baseLayer,satLayer;
function $(s){return document.querySelector(s)}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function hasM(p){return Number.isFinite(p.mapX)&&Number.isFinite(p.mapY)}function sel(){return st.points.find(p=>p.id===st.selectedId)||null}function pend(){return st.points.find(p=>!hasM(p))||null}function pc(p,s){return s==="cctv"?{x:p.x,y:p.y}:hasM(p)?{x:p.mapX,y:p.mapY}:null}
function ang(a,b,o){const d=2*a*b;if(d<=0)return 0;return Math.acos(clamp((a*a+b*b-o*o)/d,-1,1))*180/Math.PI}
function q(v){const[a,b,c]=v,ab=dist(a,b),bc=dist(b,c),ca=dist(c,a),aa=[ang(ab,ca,bc),ang(ab,bc,ca),ang(ca,bc,ab)],m=Math.min(...aa);return{maxEdge:Math.max(ab,bc,ca),minAngle:m,minAngleVertexIndex:aa.indexOf(m)}}
function status(t){const l=t.maxEdge>+ui.edgeLimit.value,a=t.minAngle<+ui.angleLimit.value,e=t.isBoundary&&(l||a);return{included:!e,valid:!l&&!a,warning:!e&&(l||a),excluded:e,tooLong:l,tooSharp:a}}
function geoDist(a,b){const Rm=6371008.8,la1=a.y*Math.PI/180,la2=b.y*Math.PI/180,dla=(b.y-a.y)*Math.PI/180,dlo=(b.x-a.x)*Math.PI/180,s=Math.sin(dla/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dlo/2)**2;return 2*Rm*Math.atan2(Math.sqrt(s),Math.sqrt(1-s))}
function normBase(){if(st.images.cctv)return st.images.cctv.width;const xs=st.points.map(p=>p.x).filter(Number.isFinite);return Math.max(1,xs.length?Math.max(...xs)-Math.min(...xs):1000)}
function sensitivity(t){if(ui.useSensitivity&&!ui.useSensitivity.checked)return null;if(!t.vertices.every(hasM))return null;const v=t.vertices,e=[[v[0],v[1]],[v[1],v[2]],[v[2],v[0]]],rs=e.map(([a,b])=>dist(a,b)>0?geoDist({x:a.mapX,y:a.mapY},{x:b.mapX,y:b.mapY})/dist(a,b):0).filter(Number.isFinite),mx=Math.max(...rs),avg=rs.reduce((a,b)=>a+b,0)/rs.length,base=normBase(),nmx=mx*base/1000,navg=avg*base/1000;let level="good",label="높음";if(nmx>SEN_CRIT){level="critical";label="매우 낮음"}else if(nmx>SEN_LOW){level="low";label="낮음"}else if(nmx>SEN_MED){level="medium";label="보통"}return{max:mx,avg,normMax:nmx,normAvg:navg,normBase:base,level,label,err1:mx,err3:mx*3}}
function ekey(a,b){return[a,b].sort((x,y)=>x-y).join("-")}function tkey(e){return e.map(p=>p._i).sort((a,b)=>a-b).join("-")}
function cc(a,b,c){const d=2*(a.x*(b.y-c.y)+b.x*(c.y-a.y)+c.x*(a.y-b.y));if(Math.abs(d)<1e-6)return{x:0,y:0,r:-1};const ux=((a.x*a.x+a.y*a.y)*(b.y-c.y)+(b.x*b.x+b.y*b.y)*(c.y-a.y)+(c.x*c.x+c.y*c.y)*(a.y-b.y))/d,uy=((a.x*a.x+a.y*a.y)*(c.x-b.x)+(b.x*b.x+b.y*b.y)*(a.x-c.x)+(c.x*c.x+c.y*c.y)*(b.x-a.x))/d;return{x:ux,y:uy,r:Math.hypot(ux-a.x,uy-a.y)}}
function buildTin(pts){if(pts.length<3)return[];const w=pts.map((p,i)=>({...p,_i:i})),b=w.reduce((o,p)=>({minX:Math.min(o.minX,p.x),minY:Math.min(o.minY,p.y),maxX:Math.max(o.maxX,p.x),maxY:Math.max(o.maxY,p.y)}),{minX:1/0,minY:1/0,maxX:-1/0,maxY:-1/0}),sp=Math.max(b.maxX-b.minX||1,b.maxY-b.minY||1),mx=(b.minX+b.maxX)/2,my=(b.minY+b.maxY)/2,s=[{id:-1,x:mx-20*sp,y:my-sp,_i:w.length},{id:-2,x:mx,y:my+20*sp,_i:w.length+1},{id:-3,x:mx+20*sp,y:my-sp,_i:w.length+2}];let tr=[{vertices:s,circle:cc(...s)}];for(const p of w){const bad=tr.filter(t=>t.circle.r>=0&&Math.hypot(p.x-t.circle.x,p.y-t.circle.y)<=t.circle.r+1e-4),em=new Map;for(const t of bad){const[a,b,c]=t.vertices;[[a,b],[b,c],[c,a]].forEach(e=>{const k=tkey(e);em.has(k)?em.delete(k):em.set(k,e)})}tr=tr.filter(t=>!bad.includes(t));for(const e of em.values()){const v=[e[0],e[1],p];tr.push({vertices:v,circle:cc(...v)})}}const out=tr.filter(t=>t.vertices.every(p=>p.id>0)).map(t=>{const v=t.vertices.map(x=>pts.find(p=>p.id===x.id)),qq=q(v),ids=v.map(p=>p.id);return{ids,vertices:v,edges:[ekey(ids[0],ids[1]),ekey(ids[1],ids[2]),ekey(ids[2],ids[0])],minAnglePointId:v[qq.minAngleVertexIndex].id,maxEdge:qq.maxEdge,minAngle:qq.minAngle,area:Math.abs((v[0].x*(v[1].y-v[2].y)+v[1].x*(v[2].y-v[0].y)+v[2].x*(v[0].y-v[1].y))/2)}}).filter(t=>t.area>.01);const use=new Map;out.forEach(t=>t.edges.forEach(e=>use.set(e,(use.get(e)||0)+1)));out.forEach(t=>t.isBoundary=t.edges.some(e=>use.get(e)===1));return out}
function bary(p,a,b,c){const d=(b.y-c.y)*(a.x-c.x)+(c.x-b.x)*(a.y-c.y);if(Math.abs(d)<1e-9)return null;const u=((b.y-c.y)*(p.x-c.x)+(c.x-b.x)*(p.y-c.y))/d,v=((c.y-a.y)*(p.x-c.x)+(a.x-c.x)*(p.y-c.y))/d,w=1-u-v;return u>=-1e-7&&v>=-1e-7&&w>=-1e-7?{u,v,w}:null}
function testAt(p){for(const t of st.triangles){if(!status(t).included||!t.vertices.every(hasM))continue;const[a,b,c]=t.vertices,bc=bary(p,a,b,c);if(!bc)continue;const mp={x:+(a.mapX*bc.u+b.mapX*bc.v+c.mapX*bc.w).toFixed(7),y:+(a.mapY*bc.u+b.mapY*bc.v+c.mapY*bc.w).toFixed(7)};return{cctv:{x:+p.x.toFixed(1),y:+p.y.toFixed(1)},map:mp,triangle:t.ids,weights:bc,sensitivity:sensitivity(t)}}return null}
function setTestPoint(p){const r=testAt(p);if(r){st.test=r;if(map)map.getView().animate({center:ol.proj.fromLonLat([r.map.x,r.map.y]),duration:180});const s=r.sensitivity,rv=s?`<span class="risk ${s.level}">좌표 신뢰도 ${s.label} · 작업 민감도 ${s.max.toFixed(2)} m/px · 정규화 ${s.normMax.toFixed(2)} m/1000px · 예상 오차 ±${s.err1.toFixed(1)}~${s.err3.toFixed(1)}m</span>`:"";ui.testResult.innerHTML=`<strong>지도 좌표 변환 결과</strong>CCTV X ${r.cctv.x}, Y ${r.cctv.y}<code>경도 ${r.map.x.toFixed(7)} / 위도 ${r.map.y.toFixed(7)}</code><span>TIN #${r.triangle.join(" - #")}</span>${rv}`}else{st.test={cctv:{x:+p.x.toFixed(1),y:+p.y.toFixed(1)},map:null};ui.testResult.textContent="선택 위치가 유효한 매칭 TIN 내부에 없습니다. 세 꼭짓점이 모두 지도와 매칭된 TIN 내부를 클릭하세요."}render()}
function clearTest(){st.test=null;ui.testResult.textContent="테스트 모드에서 CCTV TIN 내부를 클릭하면 지도 좌표가 표시됩니다."}
function px(lon,lat,z){lat=clamp(lat,-85.05112878,85.05112878);const s=Math.sin(lat*Math.PI/180),sc=TS*2**z;return{x:(lon+180)/360*sc,y:(.5-Math.log((1+s)/(1-s))/(4*Math.PI))*sc}}function ll(x,y,z){const sc=TS*2**z,n=Math.PI-2*Math.PI*y/sc;return{x:x/sc*360-180,y:180/Math.PI*Math.atan(.5*(Math.exp(n)-Math.exp(-n)))}}
function centerPx(){return px(st.views.map.lon,st.views.map.lat,st.views.map.zoom)}function m2s(c){if(map){const p=map.getPixelFromCoordinate(ol.proj.fromLonLat([c.x,c.y]));return{x:p[0],y:p[1]}}const r=cvs.map.getBoundingClientRect(),cp=centerPx(),p=px(c.x,c.y,st.views.map.zoom);return{x:r.width/2+p.x-cp.x,y:r.height/2+p.y-cp.y}}function s2m(x,y){if(map){const r=cvs.map.getBoundingClientRect(),co=map.getCoordinateFromPixel([x-r.left,y-r.top]),a=ol.proj.toLonLat(co);return{x:a[0],y:a[1]}}const r=cvs.map.getBoundingClientRect(),cp=centerPx();return ll(cp.x+x-r.left-r.width/2,cp.y+y-r.top-r.height/2,st.views.map.zoom)}
function s2w(s,x,y){if(s==="map")return s2m(x,y);const r=cvs[s].getBoundingClientRect(),v=st.views[s];return{x:(x-r.left-v.x)/v.scale,y:(y-r.top-v.y)/v.scale}}function w2s(s,p){if(s==="map")return m2s(p);const v=st.views[s];return{x:p.x*v.scale+v.x,y:p.y*v.scale+v.y}}
function hit(s,w){if(s==="map"){const a=m2s(w);for(let i=st.points.length-1;i>=0;i--){const c=pc(st.points[i],s);if(c&&dist(a,m2s(c))<=R+5)return st.points[i]}return null}const h=R/st.views[s].scale+4;for(let i=st.points.length-1;i>=0;i--){const c=pc(st.points[i],s);if(c&&dist(w,c)<=h)return st.points[i]}return null}
function rebuild(){st.triangles=buildTin(st.points);updateUi();render()}function mapEv(e){const a=ol.proj.toLonLat(e.coordinate);return{x:a[0],y:a[1]}}function setMapInteractions(on){if(!map)return;map.getInteractions().forEach(i=>i.setActive(on))}
function vworldKey(){return ui.vworldKeyInput?.value.trim()||""}function saveVworldKey(){const k=vworldKey();if(k)localStorage.setItem("tinMakerVworldKey",k);return k}
function mapSource(type){const key=vworldKey(),sat=type==="satellite";if(key)return new ol.source.XYZ({crossOrigin:"anonymous",maxZoom:MAXZ,url:`https://api.vworld.kr/req/wmts/1.0.0/${encodeURIComponent(key)}/${sat?"Satellite":"Base"}/{z}/{y}/{x}.${sat?"jpeg":"png"}`});return sat?new ol.source.XYZ({crossOrigin:"anonymous",maxZoom:MAXZ,url:""}):new ol.source.OSM({crossOrigin:"anonymous",maxZoom:MAXZ})}
function refreshMapSources(){saveVworldKey();if(baseLayer)baseLayer.setSource(mapSource("base"));if(satLayer)satLayer.setSource(mapSource("satellite"));render()}
function initMap(){if(!window.ol||map)return;baseLayer=new ol.layer.Tile({visible:true,source:mapSource("base")});satLayer=new ol.layer.Tile({visible:false,source:mapSource("satellite")});map=new ol.Map({target:"olMap",layers:[baseLayer,satLayer],view:new ol.View({center:ol.proj.fromLonLat([INIT.lon,INIT.lat]),zoom:INIT.zoom,minZoom:MINZ,maxZoom:24,constrainRotation:false})});map.on("pointerdown",e=>{const w=mapEv(e),h=hit("map",w);if(!h)return;st.selectedId=h.id;st.drag={space:"map",pointId:h.id,off:{x:pc(h,"map").x-w.x,y:pc(h,"map").y-w.y},moved:false};setMapInteractions(false);updateUi();render();e.preventDefault()});map.on("pointerdrag",e=>{if(!st.drag||st.drag.space!=="map")return;const p=st.points.find(x=>x.id===st.drag.pointId),w=mapEv(e);if(!p)return;p.mapX=+(w.x+st.drag.off.x).toFixed(7);p.mapY=+(w.y+st.drag.off.y).toFixed(7);clearTest();st.drag.moved=true;updateUi();render();e.preventDefault()});map.on("pointerup",()=>{if(st.drag&&st.drag.space==="map"){st.skipMapClick=true;setMapInteractions(true);setTimeout(()=>{st.drag=null;st.skipMapClick=false},80)}});map.on("singleclick",e=>{if(st.skipMapClick)return;mapClick(mapEv(e))});map.on("postrender",()=>renderSpace("map"));map.getView().on("change:center",()=>renderSpace("map"));map.getView().on("change:resolution",()=>renderSpace("map"));map.getView().on("change:rotation",()=>{syncRotationUi();renderSpace("map")});syncRotationUi()}
function resize(){const d=devicePixelRatio||1;for(const[k,c]of Object.entries(cvs)){const r=c.getBoundingClientRect();c.width=Math.max(1,Math.round(r.width*d));c.height=Math.max(1,Math.round(r.height*d));ctx[k].setTransform(d,0,0,d,0,0)}if(map)map.updateSize();if(st.roadview.rv)st.roadview.rv.relayout();render()}
function addPt(w){const p=pend();if(p){st.selectedId=p.id;updateUi();render();return false}st.points.push({id:st.nextId,x:+w.x.toFixed(1),y:+w.y.toFixed(1),mapX:null,mapY:null});st.selectedId=st.nextId++;clearTest();rebuild();return true}function setMapPt(p,w){p.mapX=+w.x.toFixed(7);p.mapY=+w.y.toFixed(7);clearTest();updateUi();render()}function upd(ch){const p=sel();if(p){Object.assign(p,ch);clearTest();rebuild()}}function del(){if(st.selectedId){st.points=st.points.filter(p=>p.id!==st.selectedId);st.selectedId=null;clearTest();rebuild()}}function clearPoints(){st.points=[];st.triangles=[];st.selectedId=null;clearTest();st.nextId=1;rebuild()}
function setMode(m){st.mode=m;ui.modeButtons.forEach(b=>b.classList.toggle("active",b.dataset.mode===m));cursor()}function cursor(){cvs.cctv.style.cursor=st.mode==="add"&&pend()?"not-allowed":st.mode==="test"?"copy":st.mode==="add"?"crosshair":"default";cvs.map.style.cursor="crosshair"}
function fit(s){if(s==="map"){const cs=st.points.map(p=>pc(p,"map")).filter(Boolean);if(cs.length){st.views.map.lon=cs.reduce((a,c)=>a+c.x,0)/cs.length;st.views.map.lat=cs.reduce((a,c)=>a+c.y,0)/cs.length;if(cs.length===1)st.views.map.zoom=17}else Object.assign(st.views.map,INIT);if(map)map.getView().animate({center:ol.proj.fromLonLat([st.views.map.lon,st.views.map.lat]),zoom:st.views.map.zoom,duration:160});return}const r=cvs[s].getBoundingClientRect(),img=st.images[s],pad=54;let b;if(img)b={minX:0,minY:0,maxX:img.width,maxY:img.height};else{const cs=st.points.map(p=>pc(p,s)).filter(Boolean);b=cs.length?cs.reduce((o,p)=>({minX:Math.min(o.minX,p.x),minY:Math.min(o.minY,p.y),maxX:Math.max(o.maxX,p.x),maxY:Math.max(o.maxY,p.y)}),{minX:1/0,minY:1/0,maxX:-1/0,maxY:-1/0}):{minX:0,minY:0,maxX:r.width,maxY:r.height}}const w=Math.max(1,b.maxX-b.minX),h=Math.max(1,b.maxY-b.minY),v=st.views[s];v.scale=Math.min((r.width-pad*2)/w,(r.height-pad*2)/h,1.8);v.x=(r.width-w*v.scale)/2-b.minX*v.scale;v.y=(r.height-h*v.scale)/2-b.minY*v.scale}function fitAll(){fit("map");fit("cctv");render()}
function grid(s){return}function img(s){if(s==="map")return;const im=st.images[s];if(!im||!ui.showImage.checked)return;const c=ctx[s],v=st.views[s];c.save();c.globalAlpha=.92;c.drawImage(im,v.x,v.y,im.width*v.scale,im.height*v.scale);c.restore()}
function drawTin(s){const c=ctx[s],op=+ui.warningOpacity.value/100;c.save();for(const t of st.triangles){const stt=status(t),sen=sensitivity(t);if(stt.excluded&&ui.hideExcludedTin.checked)continue;const cs=t.vertices.map(p=>pc(p,s));if(cs.some(x=>!x))continue;const ps=cs.map(p=>w2s(s,p));c.beginPath();c.moveTo(ps[0].x,ps[0].y);c.lineTo(ps[1].x,ps[1].y);c.lineTo(ps[2].x,ps[2].y);c.closePath();c.save();c.strokeStyle="rgba(255,255,255,.96)";c.lineWidth=s==="map"?5:5.5;c.stroke();c.restore();if(stt.valid&&(!sen||sen.level==="good")){c.fillStyle=s==="map"?"rgba(37,99,235,.12)":"rgba(15,118,110,.13)";c.strokeStyle=s==="map"?"rgba(37,99,235,.86)":"rgba(15,118,110,.88)";c.lineWidth=1.4}else if(stt.warning){c.fillStyle=stt.tooSharp?`rgba(180,35,24,${.08+op*.13})`:`rgba(202,107,32,${.07+op*.12})`;c.strokeStyle=stt.tooSharp?"rgba(180,35,24,.9)":"rgba(202,107,32,.86)";c.lineWidth=2;c.setLineDash([7,5])}else if(sen&&sen.level!=="good"){c.fillStyle=sen.level==="medium"?`rgba(148,98,0,${.06+op*.1})`:`rgba(180,35,24,${.07+op*.12})`;c.strokeStyle=sen.level==="medium"?"rgba(148,98,0,.88)":"rgba(180,35,24,.88)";c.lineWidth=2;c.setLineDash([4,4])}else{c.fillStyle=`rgba(202,107,32,${.06+op*.14})`;c.strokeStyle=`rgba(202,107,32,${op})`;c.lineWidth=1.1}c.fill();c.stroke();c.setLineDash([])}c.restore()}
function recs(){const m=new Map;for(const t of st.triangles){const s=status(t);if(!s.warning||!s.tooSharp)continue;const r=m.get(t.minAnglePointId)||{count:0,minAngle:1/0};r.count++;r.minAngle=Math.min(r.minAngle,t.minAngle);m.set(t.minAnglePointId,r)}return[...m.entries()].map(([pointId,o])=>({pointId,...o})).sort((a,b)=>b.count-a.count||a.minAngle-b.minAngle).slice(0,3)}
function pts(s){const c=ctx[s],rs=new Set(recs().map(x=>x.pointId));c.save();c.textAlign="center";c.textBaseline="middle";for(const p of st.points){const co=pc(p,s);if(!co)continue;const sc=w2s(s,co),se=p.id===st.selectedId;c.beginPath();c.arc(sc.x,sc.y,se?9:R,0,Math.PI*2);c.fillStyle=se?"#cc5b33":s==="map"?"#1d4ed8":"#102a43";c.fill();c.lineWidth=se?3:2;c.strokeStyle="#fff";c.stroke();if(ui.showLabels.checked){c.fillStyle="#fff";c.font="11px Segoe UI, sans-serif";c.fillText(p.id,sc.x,sc.y)}if(rs.has(p.id)){c.beginPath();c.arc(sc.x,sc.y,se?16:14,0,Math.PI*2);c.strokeStyle="#b42318";c.lineWidth=2;c.setLineDash([3,3]);c.stroke();c.setLineDash([])}}c.restore()}
function prompt(){const p=sel();if(!p||hasM(p))return;const c=ctx.map,r=cvs.map.getBoundingClientRect();c.save();c.fillStyle="rgba(255,255,255,.9)";c.strokeStyle="rgba(37,99,235,.45)";c.beginPath();if(c.roundRect)c.roundRect(18,r.height-62,Math.min(450,r.width-36),44,7);else c.rect(18,r.height-62,Math.min(450,r.width-36),44);c.fill();c.stroke();c.fillStyle="#1e3a8a";c.font="13px Segoe UI, sans-serif";c.fillText(`선택 포인트 #${p.id}의 지도 위치를 클릭하세요.`,34,r.height-35);c.restore()}
function testMark(s){if(!st.test)return;const p=s==="cctv"?st.test.cctv:st.test.map;if(!p)return;const c=ctx[s],sc=w2s(s,p);c.save();c.strokeStyle="#fff";c.lineWidth=6;c.beginPath();c.arc(sc.x,sc.y,11,0,Math.PI*2);c.moveTo(sc.x-17,sc.y);c.lineTo(sc.x+17,sc.y);c.moveTo(sc.x,sc.y-17);c.lineTo(sc.x,sc.y+17);c.stroke();c.strokeStyle="#d92d20";c.lineWidth=2.5;c.beginPath();c.arc(sc.x,sc.y,11,0,Math.PI*2);c.moveTo(sc.x-17,sc.y);c.lineTo(sc.x+17,sc.y);c.moveTo(sc.x,sc.y-17);c.lineTo(sc.x,sc.y+17);c.stroke();c.fillStyle="#d92d20";c.font="12px Segoe UI, sans-serif";c.fillText("TEST",sc.x+15,sc.y-14);c.restore()}
function renderSpace(s){const r=cvs[s].getBoundingClientRect(),c=ctx[s];c.clearRect(0,0,r.width,r.height);grid(s);img(s);drawTin(s);pts(s);testMark(s);if(s==="map"){roadviewMark();prompt()}}function render(){renderSpace("map");renderSpace("cctv")}
function updateUi(){const ss=st.triangles.map(status),sens=st.triangles.map(sensitivity).filter(Boolean),inc=ss.filter(s=>s.included).length,exc=ss.filter(s=>s.excluded).length,warn=ss.filter(s=>s.warning).length,senWarn=sens.filter(s=>s.level!=="good").length,matched=st.points.filter(hasM).length,p=sel(),rr=recs();ui.edgeValue.value=`${ui.edgeLimit.value} px`;ui.angleValue.value=`${ui.angleLimit.value}°`;ui.warningOpacityValue.value=`${ui.warningOpacity.value}%`;ui.pointCount.textContent=st.points.length;ui.matchedCount.textContent=`${matched}/${st.points.length}`;ui.tinCount.textContent=ui.hideExcludedTin.checked?inc:st.triangles.length;ui.excludedCount.textContent=exc;ui.warningCount.textContent=warn;ui.sensitivityCount.textContent=senWarn;cursor();ui.emptySelection.classList.toggle("hidden",!!p);ui.pointEditor.classList.toggle("hidden",!p);if(p&&![ui.cctvX,ui.cctvY,ui.mapX,ui.mapY].includes(document.activeElement)){ui.cctvX.value=p.x;ui.cctvY.value=p.y;ui.mapX.value=hasM(p)?p.mapX.toFixed(7):"";ui.mapY.value=hasM(p)?p.mapY.toFixed(7):""}const pe=pend();if(pe)ui.qualityAdvice.textContent=`포인트 #${pe.id}의 지도 위치를 먼저 매칭해야 다음 CCTV 포인트를 추가할 수 있습니다.`;else if(st.points.length<3)ui.qualityAdvice.textContent="CCTV 포인트 3개 이상부터 TIN 품질을 평가합니다.";else if(warn&&rr.length)ui.qualityAdvice.textContent=`내부 예각 TIN은 지도 공백 방지를 위해 유지됩니다. 후보 ${rr.map(x=>`#${x.pointId} (${x.count}개, 최소 ${x.minAngle.toFixed(1)}°)`).join(", ")}를 이동하거나 보조 포인트를 추가하세요.`;else if(senWarn){const top=sens.sort((a,b)=>b.normMax-a.normMax)[0];ui.qualityAdvice.textContent=`좌표 민감도가 높은 TIN ${senWarn}개가 있습니다. 최대 정규화 민감도 ${top.normMax.toFixed(2)} m/1000px로, 원본 이미지 폭 기준으로 비교됩니다.`}else if(exc)ui.qualityAdvice.textContent="외곽의 품질 낮은 TIN만 제외했습니다. 내부 지도 매칭 공백은 만들지 않습니다.";else ui.qualityAdvice.textContent="현재 CCTV TIN 품질과 정규화 좌표 민감도가 기준을 만족합니다."}
function down(s,e){const w=s2w(s,e.clientX,e.clientY);if(s==="cctv"&&st.mode==="test"){setTestPoint(w);return}const h=hit(s,w);if(h){st.selectedId=h.id;st.drag={space:s,pointId:h.id,off:{x:pc(h,s).x-w.x,y:pc(h,s).y-w.y}};setMode("select");updateUi();render();return}if(s==="cctv"&&st.mode==="add"){addPt(w);return}if(s==="cctv"){const v=st.views.cctv;st.pan={space:s,cx:e.clientX,cy:e.clientY,x:v.x,y:v.y};cvs.cctv.setPointerCapture?.(e.pointerId);return}updateUi();render()}
function mapClick(w){const h=hit("map",w);if(h){st.selectedId=h.id;updateUi();render();return}const p=sel();if(p)setMapPt(p,w)}
function move(s,e){if(st.pan&&st.pan.space===s){const v=st.views[s];v.x=st.pan.x+e.clientX-st.pan.cx;v.y=st.pan.y+e.clientY-st.pan.cy;render();return}if(!st.drag||st.drag.space!==s)return;const p=st.points.find(x=>x.id===st.drag.pointId),w=s2w(s,e.clientX,e.clientY);if(!p)return;clearTest();if(s==="cctv"){p.x=+(w.x+st.drag.off.x).toFixed(1);p.y=+(w.y+st.drag.off.y).toFixed(1);rebuild()}else{p.mapX=+(w.x+st.drag.off.x).toFixed(7);p.mapY=+(w.y+st.drag.off.y).toFixed(7);updateUi();render()}}function up(){st.drag=null;st.pan=null}
function cctvWheel(e){e.preventDefault();const r=cvs.cctv.getBoundingClientRect(),v=st.views.cctv,b=s2w("cctv",e.clientX,e.clientY),f=e.deltaY<0?1.14:.88;v.scale=clamp(v.scale*f,.08,12);v.x=e.clientX-r.left-b.x*v.scale;v.y=e.clientY-r.top-b.y*v.scale;render()}function setMapType(t){st.mapType=t;ui.mapTypeButtons.forEach(b=>b.classList.toggle("active",b.dataset.mapType===t));if(baseLayer&&satLayer){baseLayer.setVisible(t==="base");satLayer.setVisible(t==="satellite")}}function rotDeg(){return map?map.getView().getRotation()*180/Math.PI:0}function setMapRotationDeg(d){if(!map)return;map.getView().setRotation(clamp(d,-45,45)*Math.PI/180);syncRotationUi()}function syncRotationUi(){if(!ui.rotateSlider||!ui.rotateValue)return;const d=clamp(rotDeg(),-45,45),s=d.toFixed(1);if(document.activeElement!==ui.rotateSlider)ui.rotateSlider.value=s;ui.rotateValue.value=`${s}°`}function rotateMap(delta){setMapRotationDeg(rotDeg()+delta*180/Math.PI)}function resetMapRotation(){setMapRotationDeg(0)}
function toggleMapTools(){const open=ui.mapTools.classList.toggle("collapsed")===false;ui.mapToolsToggle.setAttribute("aria-expanded",String(open));ui.mapToolsToggle.textContent=open?"닫기":"도구"}
function rvStatus(t){ui.roadviewStatus.textContent=t}function rvTarget(){if(st.test?.map)return st.test.map;const p=sel();if(p&&hasM(p))return{x:p.mapX,y:p.mapY};if(map){const a=ol.proj.toLonLat(map.getView().getCenter());return{x:a[0],y:a[1]}}return{x:INIT.lon,y:INIT.lat}}
function kakaoGuide(){if(location.protocol==="file:")return"현재 file://로 열려 있어 Kakao 도메인 검증에 실패할 수 있습니다. 로컬 서버(http://127.0.0.1:포트)로 열고 해당 주소를 Kakao Developers > 플랫폼 > Web에 등록한 뒤, 카카오맵 API 사용 설정을 확인하세요.";return`Kakao Developers > 플랫폼 > Web에 ${location.origin} 등록 여부, JavaScript 키 사용 여부, 카카오맵 API 사용 설정을 확인하세요.`}
function loadKakao(cb){const key=ui.kakaoKeyInput.value.trim();if(!key){rvStatus("Kakao JavaScript 키를 입력하세요.");return}localStorage.setItem("tinMakerKakaoKey",key);if(window.kakao?.maps?.Roadview){cb();return}const old=document.querySelector("script[data-kakao-sdk]");if(old)old.remove();rvStatus("Kakao SDK를 불러오는 중입니다.");const sc=document.createElement("script");let done=false;const fail=m=>{if(done)return;done=true;clearTimeout(timer);rvStatus(`${m} ${kakaoGuide()}`)};const timer=setTimeout(()=>fail("Kakao SDK 응답이 지연되고 있습니다."),7000);sc.dataset.kakaoSdk="1";sc.src=`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${encodeURIComponent(key)}&autoload=false`;sc.onload=()=>{if(!window.kakao?.maps?.load){fail("Kakao SDK가 초기화되지 않았습니다. 키 종류가 JavaScript 키인지 확인하세요.");return}kakao.maps.load(()=>{if(done)return;done=true;clearTimeout(timer);cb()})};sc.onerror=()=>fail("Kakao SDK를 불러오지 못했습니다. 키가 JavaScript 키인지, 현재 주소가 허용 도메인인지 확인하세요.");document.head.appendChild(sc)}
function syncRoadview(){if(!st.roadview.enabled||!st.roadview.rv)return;const p=st.roadview.rv.getPosition?.(),vp=st.roadview.rv.getViewpoint?.();let changed=false;if(p){const np={x:p.getLng(),y:p.getLat()};changed=!st.roadview.pos||Math.abs(np.x-st.roadview.pos.x)>1e-8||Math.abs(np.y-st.roadview.pos.y)>1e-8;st.roadview.pos=np}if(vp){const ov=st.roadview.viewpoint;changed=changed||!ov||Math.abs((vp.pan??0)-(ov.pan??0))>.05||Math.abs((vp.tilt??0)-(ov.tilt??0))>.05||Math.abs((vp.zoom??0)-(ov.zoom??0))>.05;st.roadview.viewpoint=vp}if(changed)renderSpace("map")}
function startRoadviewSync(){stopRoadviewSync();syncRoadview();st.roadview.syncTimer=setInterval(syncRoadview,80)}
function stopRoadviewSync(){if(st.roadview.syncTimer){clearInterval(st.roadview.syncTimer);st.roadview.syncTimer=null}}
function initRoadview(cb){loadKakao(()=>{if(!st.roadview.rv){st.roadview.rv=new kakao.maps.Roadview(ui.roadviewEl);st.roadview.client=new kakao.maps.RoadviewClient();kakao.maps.event.addListener(st.roadview.rv,"position_changed",()=>{const p=st.roadview.rv.getPosition();if(p)st.roadview.pos={x:p.getLng(),y:p.getLat()};renderSpace("map")});kakao.maps.event.addListener(st.roadview.rv,"viewpoint_changed",()=>{st.roadview.viewpoint=st.roadview.rv.getViewpoint();renderSpace("map")});kakao.maps.event.addListener(st.roadview.rv,"init",()=>rvStatus("로드뷰가 표시되었습니다. 지도에는 카메라 위치와 방향이 표시됩니다."))}st.roadview.ready=true;cb?.()})}
function setRoadviewAt(p){initRoadview(()=>{const kp=new kakao.maps.LatLng(p.y,p.x);rvStatus("가까운 로드뷰를 찾는 중입니다.");st.roadview.client.getNearestPanoId(kp,100,(id)=>{if(!id){rvStatus("반경 100m 안에 로드뷰가 없습니다.");return}st.roadview.pos=p;st.roadview.rv.setPanoId(id,kp);setTimeout(()=>{st.roadview.rv.relayout();syncRoadview()},80);startRoadviewSync();renderSpace("map")})})}
function toggleRoadview(){st.roadview.enabled=!st.roadview.enabled;ui.roadviewPanel.classList.toggle("hidden",!st.roadview.enabled);ui.roadviewToggleBtn.classList.toggle("active",st.roadview.enabled);if(st.roadview.enabled)setRoadviewAt(rvTarget());else{stopRoadviewSync();renderSpace("map")}}
function roadviewMark(){if(!st.roadview.enabled||!st.roadview.pos)return;const c=ctx.map,p=w2s("map",st.roadview.pos),pan=st.roadview.viewpoint?.pan??0,rot=map?map.getView().getRotation():0,a=pan*Math.PI/180-rot-Math.PI/2,len=38;c.save();c.translate(p.x,p.y);c.strokeStyle="#fff";c.lineWidth=7;c.beginPath();c.moveTo(0,0);c.lineTo(Math.cos(a)*len,Math.sin(a)*len);c.stroke();c.fillStyle="#fff";c.beginPath();c.arc(0,0,12,0,Math.PI*2);c.fill();c.strokeStyle="#7c3aed";c.lineWidth=3;c.beginPath();c.moveTo(0,0);c.lineTo(Math.cos(a)*len,Math.sin(a)*len);c.stroke();c.fillStyle="#7c3aed";c.beginPath();c.arc(0,0,7,0,Math.PI*2);c.fill();c.restore()}
function readImg(s,f){const rd=new FileReader;rd.onload=()=>{const im=new Image;im.onload=()=>{st.images[s]=im;fit(s);render()};im.src=rd.result};rd.readAsDataURL(f)}function exp(){const data={version:4,createdAt:new Date().toISOString(),coordinateSystem:"WGS84",initialMapCenter:{lon:INIT.lon,lat:INIT.lat,zoom:INIT.zoom},edgeLimit:+ui.edgeLimit.value,angleLimit:+ui.angleLimit.value,points:st.points.map(({id,x,y,mapX,mapY})=>({id,cctv:{x,y},map:hasM({mapX,mapY})?{lon:mapX,lat:mapY}:null})),triangles:st.triangles.filter(t=>status(t).included).map(t=>{const sen=sensitivity(t);return{pointIds:t.ids,maxEdge:+t.maxEdge.toFixed(2),minAngle:+t.minAngle.toFixed(2),isBoundary:t.isBoundary,mapReady:t.vertices.every(hasM),quality:status(t).valid?"ok":"warning",sensitivity:sen?{maxMeterPerPixel:+sen.max.toFixed(4),avgMeterPerPixel:+sen.avg.toFixed(4),normalizedMaxMeterPer1000Pixel:+sen.normMax.toFixed(4),normalizedAvgMeterPer1000Pixel:+sen.normAvg.toFixed(4),normalizationPixelWidth:+sen.normBase.toFixed(2),confidence:sen.label,estimatedErrorMeter:{onePixel:+sen.err1.toFixed(2),threePixel:+sen.err3.toFixed(2)}}:null}})},a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="tin-points-wgs84.json";a.click();URL.revokeObjectURL(a.href)}
function imp(f){const rd=new FileReader;rd.onload=()=>{try{const d=JSON.parse(rd.result);if(!Array.isArray(d.points))throw Error("points 배열이 없습니다.");st.points=d.points.map((p,i)=>{const c=p.cctv||p,m=p.map||null,lon=m?(m.lon??m.x):p.mapX,lat=m?(m.lat??m.y):p.mapY;return{id:+p.id||i+1,x:+c.x||0,y:+c.y||0,mapX:lon!==""&&Number.isFinite(+lon)?+lon:null,mapY:lat!==""&&Number.isFinite(+lat)?+lat:null}});st.nextId=Math.max(0,...st.points.map(p=>p.id))+1;st.selectedId=null;if(d.edgeLimit)ui.edgeLimit.value=d.edgeLimit;if(d.angleLimit)ui.angleLimit.value=d.angleLimit;rebuild();fitAll()}catch(e){alert(`JSON을 불러오지 못했습니다. ${e.message}`)}};rd.readAsText(f)}
function applyKeyConfig(c){const v=(c?.vworldKey||"").trim(),k=(c?.kakaoJavaScriptKey||c?.kakaoKey||"").trim();if(v){ui.vworldKeyInput.value=v;localStorage.setItem("tinMakerVworldKey",v)}if(k){ui.kakaoKeyInput.value=k;localStorage.setItem("tinMakerKakaoKey",k)}}
async function loadKeyConfig(){try{const r=await fetch("config.local.json",{cache:"no-store"});if(!r.ok)return false;applyKeyConfig(await r.json());return true}catch{return false}}
for(const s of["map","cctv"]){cvs[s].addEventListener("pointerdown",e=>down(s,e));cvs[s].addEventListener("pointermove",e=>move(s,e));cvs[s].addEventListener("pointerup",up);cvs[s].addEventListener("pointerleave",up)}cvs.cctv.addEventListener("wheel",cctvWheel,{passive:false});addEventListener("resize",()=>{resize();fitAll()});addEventListener("keydown",e=>{const t=document.activeElement?.tagName;if((e.key==="Delete"||e.key==="Backspace")&&t!=="INPUT"&&t!=="TEXTAREA")del();if(e.key.toLowerCase()==="a")setMode("add");if(e.key.toLowerCase()==="v")setMode("select");if(e.key.toLowerCase()==="t")setMode("test")});
ui.vworldKeyInput.value=localStorage.getItem("tinMakerVworldKey")||"";ui.kakaoKeyInput.value=localStorage.getItem("tinMakerKakaoKey")||"";ui.mapToolsToggle.addEventListener("click",toggleMapTools);ui.vworldApplyBtn.addEventListener("click",refreshMapSources);ui.rotateLeft.addEventListener("click",()=>rotateMap(-Math.PI/360));ui.rotateRight.addEventListener("click",()=>rotateMap(Math.PI/360));ui.rotateReset.addEventListener("click",resetMapRotation);ui.rotateSlider?.addEventListener("input",()=>setMapRotationDeg(+ui.rotateSlider.value||0));ui.roadviewToggleBtn.addEventListener("click",toggleRoadview);ui.roadviewRefreshBtn.addEventListener("click",()=>{if(st.roadview.enabled)setRoadviewAt(rvTarget());else rvStatus("RV를 켠 뒤 위치를 갱신하세요.")});
ui.modeButtons.forEach(b=>b.addEventListener("click",()=>setMode(b.dataset.mode)));ui.mapTypeButtons.forEach(b=>b.addEventListener("click",()=>setMapType(b.dataset.mapType)));ui.fitBtn.addEventListener("click",fitAll);ui.deletePointBtn.addEventListener("click",del);ui.clearBtn.addEventListener("click",()=>{if(confirm("모든 포인트와 TIN을 삭제할까요?"))clearPoints()});ui.clearPointsBtn.addEventListener("click",()=>{if(confirm("포인트를 모두 초기화할까요?"))clearPoints()});ui.exportBtn.addEventListener("click",exp);ui.cctvImageInput.addEventListener("change",e=>{const[f]=e.target.files;if(f)readImg("cctv",f)});ui.jsonInput.addEventListener("change",e=>{const[f]=e.target.files;if(f)imp(f)});[ui.showImage,ui.showLabels,ui.hideExcludedTin,ui.edgeLimit,ui.angleLimit,ui.warningOpacity].forEach(x=>x.addEventListener("input",()=>{updateUi();render()}));ui.useSensitivity.addEventListener("input",()=>{clearTest();updateUi();render()});ui.cctvX.addEventListener("change",()=>upd({x:+ui.cctvX.value||0}));ui.cctvY.addEventListener("change",()=>upd({y:+ui.cctvY.value||0}));ui.mapX.addEventListener("change",()=>upd({mapX:ui.mapX.value===""?null:+ui.mapX.value}));ui.mapY.addEventListener("change",()=>upd({mapY:ui.mapY.value===""?null:+ui.mapY.value}));
initMap();resize();fitAll();setMapType("base");setMode("add");loadKeyConfig().then(ok=>{if(ok)refreshMapSources()});
